// <auto-generated />
using System;
using Backend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903103447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Api.Models.Categories.Category", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<long>("SortOrder")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("iv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.Credentials.Credential", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<long>("CategoryRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("favourite")
                        .HasColumnType("boolean");

                    b.Property<bool>("hideUsername")
                        .HasColumnType("boolean");

                    b.HasKey("RecordId");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.Profiles.Profile", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.HasIndex("UserRecordId");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.RecoveryCodes.RecoveryCode", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("RecordId");

                    b.HasIndex("UserRecordId");

                    b.ToTable("RecoveryCodes", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("BreachScansUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TrialReminderSent")
                        .HasColumnType("boolean");

                    b.HasKey("UserRecordId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.UserSettings", b =>
                {
                    b.Property<Guid>("UserRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("auto_lock")
                        .HasColumnType("boolean");

                    b.Property<int>("auto_lock_number")
                        .HasColumnType("integer");

                    b.Property<bool>("clipboard_clean")
                        .HasColumnType("boolean");

                    b.Property<bool>("dark_mode")
                        .HasColumnType("boolean");

                    b.Property<bool>("hide_credentials_default")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("security_alerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("twofa")
                        .HasColumnType("boolean");

                    b.HasKey("UserRecordId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.Users.User", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthChallenge")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AuthChallengeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthVerifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("KdfAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("integer");

                    b.Property<int>("KdfMemoryKib")
                        .HasColumnType("integer");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("integer");

                    b.Property<string>("KdfSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockoutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TotpEnabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TotpSecretProtected")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrappedDataKeyIv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Models.Profiles.Profile", b =>
                {
                    b.HasOne("Backend.Api.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Models.RecoveryCodes.RecoveryCode", b =>
                {
                    b.HasOne("Backend.Api.Models.Users.User", null)
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("UserRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Api.Models.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Backend.Api.Models.Users.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Backend.Api.Models.Subscriptions.Subscription", "UserRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Models.UserSettings", b =>
                {
                    b.HasOne("Backend.Api.Models.Users.User", null)
                        .WithOne("Settings")
                        .HasForeignKey("Backend.Api.Models.UserSettings", "UserRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Api.Models.Users.User", b =>
                {
                    b.Navigation("RecoveryCodes");

                    b.Navigation("Settings");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
